# -*- coding: utf-8 -*-
"""Best selling product identification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GTZxWMNrem9YrnfiFmjzFf5OZYGJc6Jq
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN
from sklearn.mixture import GaussianMixture
from sklearn.metrics import silhouette_score
from sklearn.decomposition import PCA

from scipy.cluster.hierarchy import dendrogram, linkage

import warnings
warnings.filterwarnings("ignore")


def plot_clusters(X_pca, labels, title):

    plt.figure(figsize=(8,6))

    if X_pca.shape[1] == 1:
        plt.scatter(X_pca[:,0], np.zeros(len(X_pca)), c=labels)
        plt.xlabel("PC1")
        plt.yticks([])
    else:
        plt.scatter(X_pca[:,0], X_pca[:,1], c=labels)
        plt.xlabel("PC1")
        plt.ylabel("PC2")

    plt.title(title)
    plt.show()


df = pd.read_csv("Combined_dataset.csv")

df.columns = df.columns.str.lower().str.strip().str.replace(" ", "_")

print("Dataset Shape:", df.shape)


required_columns = [
    "rating",
    "ratings_count",
    "initial_price",
    "final_price",
    "discount"
]

missing = [col for col in required_columns if col not in df.columns]

if missing:
    raise ValueError(f"Dataset missing required columns: {missing}")


df.drop_duplicates(inplace=True)


numeric_features = [
    "rating",
    "ratings_count",
    "initial_price",
    "final_price",
    "discount"
]

for col in numeric_features:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df.fillna(0, inplace=True)


df["sales_score"] = df["rating"] * df["ratings_count"]

df["discount_percent"] = (
    (df["initial_price"] - df["final_price"]) /
    df["initial_price"]
) * 100

df.replace([np.inf, -np.inf], 0, inplace=True)


features = [
    "rating",
    "ratings_count",
    "initial_price",
    "final_price",
    "discount",
    "sales_score",
    "discount_percent"
]

X = df[features]

print("Features Used:", features)


scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


pca = PCA(n_components=min(2, X.shape[1]))
X_pca = pca.fit_transform(X_scaled)


linked = linkage(X_scaled, method="ward")

plt.figure(figsize=(12,6))
dendrogram(linked)
plt.title("Hierarchical Clustering Dendrogram")
plt.xlabel("Products")
plt.ylabel("Distance")
plt.show()


wcss = []
silhouette_scores = []

cluster_range = range(2,10)

for i in cluster_range:

    kmeans = KMeans(n_clusters=i, random_state=42)

    labels = kmeans.fit_predict(X_scaled)

    wcss.append(kmeans.inertia_)

    silhouette_scores.append(
        silhouette_score(X_scaled, labels)
    )


plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
plt.plot(cluster_range, wcss, marker="o")
plt.title("Elbow Method")

plt.subplot(1,2,2)
plt.plot(cluster_range, silhouette_scores, marker="o")
plt.title("Silhouette Score")

plt.show()


optimal_clusters = 3

kmeans = KMeans(
    n_clusters=optimal_clusters,
    random_state=42
)

kmeans_labels = kmeans.fit_predict(X_scaled)

df["kmeans_cluster"] = kmeans_labels

plot_clusters(X_pca, kmeans_labels, "KMeans Clustering")


hc = AgglomerativeClustering(
    n_clusters=optimal_clusters
)

hc_labels = hc.fit_predict(X_scaled)

df["hierarchical_cluster"] = hc_labels

plot_clusters(X_pca, hc_labels, "Hierarchical Clustering")


gmm = GaussianMixture(
    n_components=optimal_clusters
)

gmm_labels = gmm.fit_predict(X_scaled)

df["gaussian_cluster"] = gmm_labels

plot_clusters(X_pca, gmm_labels, "Gaussian Mixture Clustering")


dbscan = DBSCAN(
    eps=0.7,
    min_samples=8
)

dbscan_labels = dbscan.fit_predict(X_scaled)

df["dbscan_cluster"] = dbscan_labels

plot_clusters(X_pca, dbscan_labels, "DBSCAN Clustering")


cluster_summary = df.groupby(
    "kmeans_cluster"
)[features].mean()

print(cluster_summary)


best_cluster = cluster_summary["sales_score"].idxmax()

print("Best Selling Cluster:", best_cluster)

best_products = df[df["kmeans_cluster"] == best_cluster]

print("Top Best Selling Products")
print(best_products[["title","rating","ratings_count","final_price"]].head())


df.to_csv(
    "clustered_products.csv",
    index=False
)


plot_clusters(
    X_pca,
    df["kmeans_cluster"],
    "Final Product Clusters"
)

print("Model Completed Successfully")